import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Funnel_Sans, Funnel_Display } from "next/font/google";
import { ThemeToggle } from "./components/ThemeToggle/ThemeToggle";
import "./globals.css";

const geistSans = Funnel_Sans({
  variable: "--font-funnel-sans",
  subsets: ["latin"],
});

const geistMono = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} transition-colors duration-300 ease-in-out min-w-[350px]`}
      >
        <ThemeProvider
          attribute={"data-theme"}
          defaultTheme="myLightTheme"
          enableSystem={false}
          themes={["myLightTheme", "myDarkTheme"]}
        >
          {children}
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
